# Generated by Django 2.1.3 on 2018-11-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehub', '0002_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Designing', 'Designing'), ('Coding', 'Coding'), ('Cooking', 'Cooking'), ('Photography', 'Photography'), ('Writing', 'Writing'), ('Traveling', 'Traveling'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
