# Generated by Django 2.1.3 on 2018-12-12 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thehub', '0008_memberrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
    ]
